server:
  port: 8080
spring:
  application:
    name: kafka-test
  kafka:
    bootstrap-servers: 106.14.142.184:9092,106.14.142.184:9093,106.14.142.184:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息确认方式
      acks: 1
      # 消息发送失败重试次数
      retries: 10
    consumer:
      # 消费组id
      group-id: ${spring.application.name}-test
      # 是否开启自动提交
#      enable-auto-commit: false
      # 自动将偏移量置为earliest、latest、none
      auto-offset-reset: earliest
      # 每次消费时最大拉取消息条数
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
      # concurrency就是同组下的消费者个数,就是并发消费的消费数,一般设置值小于分区个数
      # 消费者数小于分区数
      concurrency: 3
      ack-mode: MANUAL
